// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarehouseManagementSystem.Server.Data;

namespace WarehouseManagementSystem.Server.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20201205051259_firstcreate")]
    partial class firstcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("WarehouseManagementSystem.Shared.ArticleMaster", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Article_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Article_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Article_Short_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Assortment_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Assortment_status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Base_Unit_of_Measure")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Division")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gross_Weight_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gross_Weight_PC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Height_PC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Length_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Length_PC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Listing_Module")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Merchandise_Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Net_Weight_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Net_Weight_PC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Primary_Price_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Secondary_Price_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit_Conversion1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit_Conversion2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit_Conversion3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uom1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uom2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uom3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Updated_Date")
                        .HasColumnType("date");

                    b.Property<string>("Volume_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_CS_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_PC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Volume_PC_L")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Width_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Width_PC")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Article_Masters");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.BusinessPartner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Banner_ID_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Card_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Changed_date")
                        .HasColumnType("date");

                    b.Property<string>("Classification")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Classification_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact_Person")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Created_On")
                        .HasColumnType("date");

                    b.Property<DateTime>("Deactivation_date")
                        .HasColumnType("date");

                    b.Property<string>("Delivering_Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivering_Site_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("House_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LSR_Barangay_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LSR_City_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LSR_Level_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LSR_Province_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Latitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lead_Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Longitude")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MAG_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mobile")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outlet_Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outlet_Sub_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outlet_Sub_Type_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outlet_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outlet_Type_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PJP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payment_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Payment_Type_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Perfect_Store_Audit_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Postal_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Requestor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Search_Term1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Search_Term2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street_3")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tax1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terms_of_Payment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terms_of_Payment_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VAT_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("eRTM")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Business_Partners");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.BusinessUnit", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Business_Unit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cost_Center")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Group_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Business_Units");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.DeliveryReceipt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Aggr_Pieces")
                        .HasColumnType("int");

                    b.Property<string>("Billing_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Billing_Type_1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Cabinet_Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("Calendar_Day")
                        .HasColumnType("date");

                    b.Property<int>("Coupon_Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("DT_Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Delivery_Due_Date")
                        .HasColumnType("date");

                    b.Property<string>("Delivery_Receipt_No")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Distributor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Distributor_Desc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Free_Qty_Aggr_CS")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Free_Qty_Aggr_PC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Free_Qty_CS")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Free_Qty_Liter")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Free_Qty_PC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GSV")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Lead_Basepack")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Master_Basepack")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Master_Basepack_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Master_Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Master_Brand_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Master_FSS")
                        .HasColumnType("int");

                    b.Property<string>("Master_FSS_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Master_Outlet_City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Master_Outlet_City_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Master_Outlet_Subtype")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Master_Outlet_Subtype_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("NIV")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Outlet_Code")
                        .HasColumnType("int");

                    b.Property<string>("Outlet_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pack_Size")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Product_Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Product_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Purchase_Order_No")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Route_Desc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Sales_After")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Sales_Order_No")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Sales_Qty_Aggr_CS")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Sales_Qty_Aggr_PC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Sales_Qty_CS")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Sales_Qty_Liter")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Sales_Qty_PC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Sales_Route")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Salesman_Id")
                        .HasColumnType("int");

                    b.Property<string>("Salesman_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Salesman_Team_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Salesman_Team_Type_Desc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Site")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Site_Desc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TPR")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Terms_Of_Payment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Total_Sales_Amnt_Inc")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UW")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("VAT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Volume_Discount")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ID");

                    b.ToTable("Delivery_Receipts");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.Discount", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Customer_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount_Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.Inventory", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Item_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Transaction_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Warehouse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Inventories");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.InventoryDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Header_Ref")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Transaction_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Uom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Warehouse")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Inventory_Details");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.InventoryHeader", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Item_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ref_ID")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Inventory_Headers");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.Location", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DamageLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiftLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalesLocation")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.PurchaseDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("Document_Date")
                        .HasColumnType("date");

                    b.Property<int>("Header_ID")
                        .HasColumnType("int");

                    b.Property<string>("Item_Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Item_Desc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Posting_Date")
                        .HasColumnType("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Site")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Uom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Purchase_Details");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.PurchaseHeaders", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Article_Doc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Bill_Doc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.ToTable("Purchase_Headers");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.PurchaseOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Article_Doc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Bill_Doc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Document_Date")
                        .HasColumnType("date");

                    b.Property<string>("Item_Code")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Item_Desc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("Posting_Date")
                        .HasColumnType("date");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Site")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Uom")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Purchase_Orders");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.SAPSalesmanMaster", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DamageLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GiftLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SAP_Salesman_Code")
                        .HasColumnType("int");

                    b.Property<string>("SalesLoc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salesman_Code")
                        .HasColumnType("int");

                    b.Property<int>("Salesman_Customer_Code")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("SAP_SalesmanMasters");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.SalesInvoice", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Aggr_Pieces")
                        .HasColumnType("int");

                    b.Property<string>("Billing_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Billing_Type_1")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Cabinet_Count")
                        .HasColumnType("int");

                    b.Property<DateTime>("Calendar_Day")
                        .HasColumnType("date");

                    b.Property<int>("Coupon_Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("DT_Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Distributor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Distributor_Desc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Free_Qty_Aggr_CS")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Free_Qty_Aggr_PC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Free_Qty_CS")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Free_Qty_Liter")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Free_Qty_PC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GSV")
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("Invoice_Due_Date")
                        .HasColumnType("date");

                    b.Property<string>("Invoice_No")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Lead_Basepack")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Master_Basepack")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Master_Basepack_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Master_Brand")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Master_Brand_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Master_FSS")
                        .HasColumnType("int");

                    b.Property<string>("Master_FSS_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Master_Outlet_City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Master_Outlet_City_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Master_Outlet_Subtype")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Master_Outlet_Subtype_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("NIV")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Outlet_Code")
                        .HasColumnType("int");

                    b.Property<string>("Outlet_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Pack_Size")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Product_Id")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Product_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Purchase_Order_No")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Route_Desc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Sales_After")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Sales_Order_No")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Sales_Qty_Aggr_CS")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Sales_Qty_Aggr_PC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Sales_Qty_CS")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Sales_Qty_Liter")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Sales_Qty_PC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Sales_Route")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Salesman_Id")
                        .HasColumnType("int");

                    b.Property<string>("Salesman_Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Salesman_Team_Type")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Salesman_Team_Type_Desc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Site")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Site_Desc")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("TPR")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Terms_Of_Payment")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Total_Sales_Amnt_Inc")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UW")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("VAT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Volume_Discount")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ID");

                    b.ToTable("Sales_Invoice");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.SalesInvoice_Details", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Aggr_Pieces")
                        .HasColumnType("int");

                    b.Property<int>("Cabinet_Count")
                        .HasColumnType("int");

                    b.Property<int>("Coupon_Discount")
                        .HasColumnType("int");

                    b.Property<decimal>("DT_Discount")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Free_Qty_Aggr_CS")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Free_Qty_Aggr_PC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Free_Qty_CS")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Free_Qty_Liter")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Free_Qty_PC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("GSV")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Header_ID")
                        .HasColumnType("int");

                    b.Property<string>("Lead_Basepack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master_Basepack")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master_Basepack_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master_Brand")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master_Brand_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("NIV")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Pack_Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Id")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Sales_After")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Sales_Qty_Aggr_CS")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Sales_Qty_Aggr_PC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Sales_Qty_CS")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Sales_Qty_Liter")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Sales_Qty_PC")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("TPR")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Total_Sales_Amnt_Inc")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("UW")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("VAT")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Volume_Discount")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ID");

                    b.ToTable("SalesInvoice_Details");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.SalesInvoice_Headers", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Billing_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Billing_Type_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Calendar_Day")
                        .HasColumnType("date");

                    b.Property<string>("Distributor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Distributor_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Invoice_Due_Date")
                        .HasColumnType("date");

                    b.Property<string>("Invoice_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Master_FSS")
                        .HasColumnType("int");

                    b.Property<string>("Master_FSS_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master_Outlet_City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master_Outlet_City_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master_Outlet_Subtype")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Master_Outlet_Subtype_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Outlet_Code")
                        .HasColumnType("int");

                    b.Property<string>("Outlet_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purchase_Order_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sales_Order_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sales_Route")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Salesman_Id")
                        .HasColumnType("int");

                    b.Property<string>("Salesman_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Team_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Team_Type_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terms_Of_Payment")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("SalesInvoice_Headers");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.SalesOrder", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Article_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cases_Pieces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_Free_Qty_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_Free_Qty_PC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_N")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_Qty_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_Qty_PC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Document_Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Free_CS_PS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Free_Cases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Free_Piece")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Item_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material_N")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Net_Sales")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Order_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Type_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outlet_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outlet_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pack_Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pieces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SO_Date")
                        .HasColumnType("date");

                    b.Property<decimal>("Sales_Value")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Salesman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terms_of_payment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Turnover_Value")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("VAT_Value")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ID");

                    b.ToTable("Sales_Orders");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.SalesOrderDetails", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Article_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cases_Pieces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_Qty_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_Qty_PC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Free_CS_PS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Free_Cases")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Free_Piece")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Header_ID")
                        .HasColumnType("int");

                    b.Property<string>("Item_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Material_N")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Net_Sales")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Pack_Size")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pieces")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Sales_Value")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("VAT_Value")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ID");

                    b.ToTable("SalesOrder_Details");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.SalesOrderHeaders", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Delivery_Free_Qty_CS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_Free_Qty_PC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Delivery_N")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Document_Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Type_Desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outlet_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Outlet_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route_No")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Route_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SO_Date")
                        .HasColumnType("date");

                    b.Property<string>("Salesman")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Terms_of_payment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Turnover_Value")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("ID");

                    b.ToTable("SalesOrder_Headers");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.SalesmanMaster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address_1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address_2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date_of_Birth")
                        .HasColumnType("date");

                    b.Property<string>("Education")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End_Date")
                        .HasColumnType("date");

                    b.Property<string>("FSS_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FSS_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Legacy_Salesman_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PDA_Flag")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PDA_Flag_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Group")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Grp_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sales_Route")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sales_Route_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Team_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Team_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salesman_Type_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site_desc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Start_Date")
                        .HasColumnType("date");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status_Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Warehouse_Distributor")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Salesman_Masters");
                });

            modelBuilder.Entity("WarehouseManagementSystem.Shared.Warehouse", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("SiteCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Warehouses");
                });
#pragma warning restore 612, 618
        }
    }
}
